version: 2

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        formats: 
          - zip
dockers:
  - image_templates:
    - "ghcr.io/fmotalleb/timber:latest"
    - "ghcr.io/fmotalleb/timber:{{ .Major }}"
    - "ghcr.io/fmotalleb/timber:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/fmotalleb/timber:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
release:
  github:
    name: timber
    owner: fmotalleb
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
